### ISSUE TITLE
how to make this work for Lumen?

### ISSUE THREAD

**Issue by zackyjack** [beyondcode/laravel-dump-server#11]
when I install it for Lumen (including copy config file and add its service provider to /bootstrap/app.php), I get this error when running `php artisan`:

```
In DumpServerServiceProvider.php line 21:

  Call to undefined function BeyondCode\DumpServer\config_path()
```

is it possible to use this package in Lumen? if so, what should I do?

**Comment by mstaack** [comment]
see https://github.com/beyondcode/laravel-dump-server/pull/13
