### ISSUE TITLE
Any possibility for 5.5 support?

### ISSUE THREAD

**Issue by fullstackfool** [beyondcode/laravel-dump-server#15]
Love to use this, any chance of Laravel 5.5 support?

**Comment by Patryk27** [comment]
It works fine with 5.6, so I believe 5.5 shouldn't cause any trouble either - can you paste any error message, if you receive any?

**Comment by vzool** [comment]
It is not supported in 5.5
Check this #3 old issue

**Comment by fullstackfool** [comment]
Ah, apologies, should have checked closed tickets.
