### ISSUE TITLE
Customize host and port

### ISSUE THREAD

**Issue by nianwang** [beyondcode/laravel-dump-server#31]
Is it possible to customize the host and port and continuously pipe the output?

Currently, it appears the hostname/port is hard-coded to `tcp://127.0.0.1:9912` via _config/config.php_.

A possible syntax similar to the following is recommended:

```
# following Laravel "php artisan serve" convention
php artisan dump-server --host="$HOST" --port="$PORT"
```

This way, we can avoid conflicts with other running services, especially those that allow automatically mapping host/port to local, user-friendly variants. For example, [typicode/hotel](https://github.com/typicode/hotel).

**Comment by nianwang** [comment]
Especially since this is for debugging (local development), it looks like follow convention is to publish the config, which can then be overridden:

```
php artisan vendor:publish --tag=config
```

... then edit the resulting _config/debug-server.php_ as needed. Perhaps a _README.md_ update, then.

**Comment by lucasmichot** [comment]
@mpociot I go through the same issue with the cli
What about https://github.com/laravel/framework/blob/e6c8aa0e39d8f91068ad1c299546536e9f25ef63/src/Illuminate/Foundation/Console/ServeCommand.php#L45-L54 ?

**Comment by twigs67** [comment]
Any word on this? It would be great to add a port.

**Comment by BasvanH** [comment]
It's now settable via `.env`

```
DUMP_SERVER_HOST=tcp://127.0.0.1:9912
```
