### ISSUE TITLE
Support 4 laravel 6.x

### ISSUE THREAD

**Issue by Samuel-Bie** [beyondcode/laravel-dump-server#56]
Sory this is not an issue, i just want to know if there is a plan of supporting laravel 6>.

Thanks 4 a great pkg

**Comment by erhuz** [comment]
I believe the package already supports laravel ^6.0

**Comment by Samuel-Bie** [comment]
@erhuz are you using it in any version of laravel 6

**Comment by erhuz** [comment]
@Samuel-Bie I was, since today I'm using it with laravel 7

**Comment by erhuz** [comment]
@Samuel-Bie Have you made it work with laravel 6?

**Comment by erhuz** [comment]
@Samuel-Bie is it working out for you?

**Comment by Samuel-Bie** [comment]
Its not working on laravel 6.2

**Comment by Samuel-Bie** [comment]
@erhuz  Its working on laravel 7.
