### ISSUE TITLE
Problem installing Laravel 6

### ISSUE THREAD

**Issue by scaleman114** [beyondcode/laravel-dump-server#62]
This looks really useful but when I install I get this.
Have tried php artisan config:clear and composer update symfony/var-dumper...

Using version ^1.4 for beyondcode/laravel-dump-server
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for beyondcode/laravel-dump-server ^1.4 -> satisfiable by beyondcode/laravel-dump-server[1.4.0].
    - Conclusion: remove symfony/var-dumper v4.4.5
    - Conclusion: don't install symfony/var-dumper v4.4.5
    - beyondcode/laravel-dump-server 1.4.0 requires symfony/var-dumper ^5.0 -> satisfiable by symfony/var-dumper[5.0.x-dev, 5.1.x-dev, v5.0.0, v5.0.0-BETA1, v5.0.0-BETA2, v5.0.0-RC1, v5.0.1, v5.0.2, v5.0.3, v5.0.4, v5.0.5].
    - Can only install one of: symfony/var-dumper[5.0.x-dev, v4.4.5].
    - Can only install one of: symfony/var-dumper[5.1.x-dev, v4.4.5].
    - Can only install one of: symfony/var-dumper[v5.0.0, v4.4.5].
    - Can only install one of: symfony/var-dumper[v5.0.0-BETA1, v4.4.5].
    - Can only install one of: symfony/var-dumper[v5.0.0-BETA2, v4.4.5].
    - Can only install one of: symfony/var-dumper[v5.0.0-RC1, v4.4.5].
    - Can only install one of: symfony/var-dumper[v5.0.1, v4.4.5].
    - Can only install one of: symfony/var-dumper[v5.0.2, v4.4.5].
    - Can only install one of: symfony/var-dumper[v5.0.3, v4.4.5].
    - Can only install one of: symfony/var-dumper[v5.0.4, v4.4.5].
    - Can only install one of: symfony/var-dumper[v5.0.5, v4.4.5].
    - Installation request for symfony/var-dumper (locked at v4.4.5) -> satisfiable by

**Comment by itank** [comment]
1.3 version seems to be working

**Comment by hofmannsven** [comment]
Installation with Laravel 6:
```
composer require --dev beyondcode/laravel-dump-server:1.3.0
```

**Comment by bluesea1234** [comment]
### 

- 

- 

- 

- 

- 

- __[drfgdf

1. 

- [ ] 

- [ ] 

- [ ] 

- [ ]                    #############@@@@@@@

](url)
