### ISSUE TITLE
`dump` never works, `dd` does

### ISSUE THREAD

**Issue by brendt** [beyondcode/laravel-dump-server#63]
Not sure what more info I can provide? This issue only started recently, `dump` doesn't write to the dump server anymore, while `dd` does.

**Comment by patrickomeara** [comment]
I'm also having this issue. There has been some inconsistent behaviour.

@brendt Did you try subsequent `dump()`?

https://github.com/beyondcode/laravel-dump-server/issues/54

**Comment by brendt** [comment]
I have not, I will the next time I'm debugging and come back with results.

**Comment by strotgen** [comment]
Hi! I'm having this issue too. Was anyone able to solve it?

Using Homestead, Laravel 8.24 and latest version of dump-server.

**Comment by patrickomeara** [comment]
I moved to Ray https://myray.app/

**Comment by caugner** [comment]
I'm using the latest Laravel (8.46) and Laravel-Dump-Server (1.7.0) version and neither `dd` nor `dump` works for me. 🤷

**Comment by brendt** [comment]
I'm going to close this issue, it's been inactive and there are better alternatives to laravel-dump-server these days. I use [Ray](https://myray.app/) as well.
