### ISSUE TITLE
Bump for 8.0

### ISSUE THREAD

**Issue by AdamKyle** [beyondcode/laravel-dump-server#69]
Laravel 8.0 just released, any idea when this package will support it?

**Comment by ahoiroman** [comment]
Will be done with the merge of https://github.com/beyondcode/laravel-dump-server/pull/67

**Comment by ShawnCorrigan** [comment]
The PR has been opened for 10 days now so I'm not sure that it's being recognized. Do we have any idea what a time frame would be for that to be approved?

**Comment by rickmills** [comment]
Seconded, this is the only package holding up a lot of standard laravel setups from upgrading now. Not sure who needs tagging to get this done however.

**Comment by mpociot** [comment]
I just tagged 1.5.0 with Laravel 8 support 👍

**Comment by ShawnCorrigan** [comment]
Wonderful thank you!
