### ISSUE TITLE
not working on windows

### ISSUE THREAD

**Issue by scplay** [beyondcode/laravel-dump-server#7]
follow the instruction and use same version of php, it not work
![image](https://user-images.githubusercontent.com/7413214/42547263-c32314f2-84f3-11e8-8b64-3e58f9f58d0a.png)
![image](https://user-images.githubusercontent.com/7413214/42547273-d0f2e1d4-84f3-11e8-85ed-69cb17ce3d4b.png)
![image](https://user-images.githubusercontent.com/7413214/42547292-e58c9c7a-84f3-11e8-9c8c-89f42426e303.png)

**Comment by mpociot** [comment]
Can someone on windows help me out on this?

**Comment by aledmb** [comment]
yep, it's not intercepting dump calls for me too on windows.

**Comment by TobyMaxham** [comment]
Hi,
to get this working on Windows you need to change your configuration file `debug-server.php`. Seems like **0.0.0.0** does not work on Windows.

```php
<?php // config/debug-server.php

return [
    /*
     * The host to use when listening for debug server connections.
     */
    'host' => 'tcp://127.0.0.1:9912',
];
```

You can edit the configuration by publishing the package configuration:
```bash
php artisan vendor:publish --provider=BeyondCode\\DumpServer\\DumpServerServiceProvider
```

This worked for me.

Regards
TobyMaxham

**Comment by aledmb** [comment]
@TobyMaxham thank you for the solution... but that command does not generate any files for me in the config directory.

```
> C:\dev\php\php.exe C:\dev\tramittar\artisan vendor:publish --provider=BeyondCode\\DumpServer\\DumpServerServiceProvider
Publishing complete.

Process finished with exit code 0 at 11:44:33.
Execution time: 752 ms.
```

**Comment by aledmb** [comment]
@TobyMaxham thank you for the solution... but that command does not generate any files for me in the config directory.

```
> artisan vendor:publish --provider=BeyondCode\\DumpServer\\DumpServerServiceProvider
Publishing complete.

Process finished with exit code 0 at 11:44:33.
Execution time: 752 ms.
```

**Comment by Rigby90** [comment]
@aledmb 

I had a similar issue, in the end I just copied the configuration file from the vendor directly and created the 'debug-server.php' within the config folder of Laravel.

You should be able to copy @TobyMaxham snippet above and just create the 'debug-server.php' manually. The config file is the only asset to publish to get this working and it only contains the single config value as shown in the snippet.

**Comment by edvordo** [comment]
On windows it's only one backslash :)

Also, you can skip the `--provider` option and just do `php artisan vendor:publish` and it will let you see the "publishable" providers with a numeric index to pick from.

Thanks @TobyMaxham for that IP change, fixed it for me.

**Comment by aledmb** [comment]
@edvordo good god... that was so clear to see! :D 

thank you!

**Comment by mpociot** [comment]
I want to close this issue: Does setting the host IP to 127.0.0.1 fix this on Windows?

**Comment by edvordo** [comment]
Yes, it does.

**Comment by mpociot** [comment]
Thank you. I changed the default config value to be `127.0.0.1` so it will work out of the box in future versions.

**Comment by sunscreem** [comment]
Quick tip here for anyone reading this and is using windows + homestead.

You need to run `php artisan dump-server` from within homestead, not locally.
