### ISSUE TITLE
Dump server not working anymore on Laravel 7.28.4

### ISSUE THREAD

**Issue by nnerijuss** [beyondcode/laravel-dump-server#71]
After upgrading Laravel 7 to latest 7.28.4 version, dump server stopped working. Dump servers starts as usual, but output goes not to terminal but to the browser.

PHP 7.4
Laravel 7.28.4
laravel-dump-server ^1.6

**Comment by Stenfrank** [comment]
The same problem

PHP 7.4.11
Laravel 7.28.4
laravel-dump-server ^1.2

**Comment by Stenfrank** [comment]
> El mismo problema
> 
> PHP 7.4.11
> Laravel 7.28.4
> laravel-dump-server ^1.2

Go back to version laravel-dump-server 1.5.0 and it worked without problems

**Comment by nnerijuss** [comment]
> > El mismo problema
> > PHP 7.4.11
> > Laravel 7.28.4
> > laravel-dump-server ^1.2
> 
> Go back to version laravel-dump-server 1.5.0 and it worked without problems

Thanks, downgrading to 1.5 helped me too.

**Comment by manu-lopez** [comment]
After downgrading, the dump-server started to work again.
Thanks.
