### ISSUE TITLE
Does not seem to work with latest laravel 8 and dump-server

### ISSUE THREAD

**Issue by Ilyes512** [beyondcode/laravel-dump-server#73]
I am using the latest versions of laravel (v8.11.2) and this library (v1.6.0) without any adjustments to the config file. It used to work pre-laravel 8. I can start the server (php artisan dump-server) and that does seem just fine... but dumps are not being catched. 

Are more people having this problem?

Edit:
This fixes it: https://github.com/beyondcode/laravel-dump-server/pull/72

**Comment by JieAnthony** [comment]
yes,I found this problem
Bug? @Ilyes512

**Comment by duxthefux** [comment]
we're also experiencing that

**Comment by nnerijuss** [comment]
Same here. Works only with 1.5 version.

**Comment by kiwina** [comment]
i can confirm 1.5 works

**Comment by Ilyes512** [comment]
Ping @mpociot ...  Can we get #72 merged, together with a new release?

**Comment by sjess** [comment]
same issue, not using 1.6, forced 1.5 now ... @mpociot

**Comment by mpociot** [comment]
Should be fixed in 1.7 now, sorry :)
