### ISSUE TITLE
not working in docker

### ISSUE THREAD

**Issue by Spartaques** [beyondcode/laravel-dump-server#74]
Hello. I have instaled laravel v7.28.4, laravel-dump-server v1.6.0,  php v7.4 and app working on Docker.
 
I have a config 
![image](https://user-images.githubusercontent.com/29341175/98348639-af2e7880-2021-11eb-9c5c-b577d303c3f6.png)

and when i use dump()  in my app i see output in the main app.

My dump server looks like this and dont changes:

![image](https://user-images.githubusercontent.com/29341175/98348779-db49f980-2021-11eb-9577-76344738b808.png)

Help me please fix this issue.

**Comment by Fighix** [comment]
Try using 1.5 ?
`composer remove beyondcode/laravel-dump-server`
`composer require beyondcode/laravel-dump-server:1.5`

**Comment by Ilyes512** [comment]
See https://github.com/beyondcode/laravel-dump-server/issues/73

**Comment by mpociot** [comment]
Should be fixed in 1.7 now, sorry :)
